### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Hmerin**
Create a code of conduct for participants and contributors to follow.

Is based on a existing template, I just added the link to the FCC VE community to find help if someone has to report something.

### CODE REVIEW

**Comment by darthzyklus** [comment]
Reviewing it.

**Comment by Gracrys** [comment]
looks fine for me

**Comment by darthzyklus** [comment]
I agree with this commit, but more important I subscribe to this code of conduct as a member and maintainer of this project.

Let's move on!

**Review by darthzyklus — APPROVED** [review]
I agree with this commit, but more important I subscribe to this code of conduct as a member and maintainer of this project.

Let's move on!

**Comment by darthzyklus** [comment]
it looks better.

**Pull request merged**
